runCDPipeline(application: "hello-service",
              devProject: "proyecto-base-dev",
              testProject: "proyecto-base-test",
              prodProject: "demo-pipelines",
              agent: "maven",
              compileCommands: "mvn clean install -DskipTests",
              testCommands: "",
              artifactFile: "./target/hello-service-1.jar",
              applicationTemplate: "./openshift/template.yaml")
  
