runCDPipelineArgo(application: "hello-service",
              devProject: "proyecto-base-dev",
              qaProject: "proyecto-base-test",
              uatProject: "proyecto-base-uat",
              prodProject: "check-conexiones",
              agent: "maven",
              compileCommands: "mvn clean install -DskipTests",
              testCommands: "",
              artifactFile: "./target/hello-service-1.jar",
              applicationTemplate: "./openshift/template.yaml",
              repoManifests: "ssh://git@10.10.103.100/manifests/hello-world")
  